-- AlterTable
ALTER TABLE "MailBox" ALTER COLUMN "emailAddress" DROP NOT NULL,
ALTER COLUMN "provider" DROP NOT NULL,
ALTER COLUMN "isActive" SET DEFAULT true,
ALTER COLUMN "lastSyncedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
